{"name": "test_practice_author_books", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome=131.0.6778.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n0   chromedriver                        0x000000010292bb08 cxxbridge1$str$ptr + 3651580\n1   chromedriver                        0x0000000102924358 cxxbridge1$str$ptr + 3620940\n2   chromedriver                        0x000000010238c4b4 cxxbridge1$string$len + 89224\n3   chromedriver                        0x0000000102391398 cxxbridge1$string$len + 109420\n4   chromedriver                        0x0000000102393688 cxxbridge1$string$len + 118364\n5   chromedriver                        0x000000010240a950 cxxbridge1$string$len + 606500\n6   chromedriver                        0x000000010240a0fc cxxbridge1$string$len + 604368\n7   chromedriver                        0x00000001023c50b0 cxxbridge1$string$len + 321668\n8   chromedriver                        0x00000001023c5d00 cxxbridge1$string$len + 324820\n9   chromedriver                        0x00000001028f6e4c cxxbridge1$str$ptr + 3435328\n10  chromedriver                        0x00000001028fa164 cxxbridge1$str$ptr + 3448408\n11  chromedriver                        0x00000001028de1c0 cxxbridge1$str$ptr + 3333812\n12  chromedriver                        0x00000001028faa24 cxxbridge1$str$ptr + 3450648\n13  chromedriver                        0x00000001028cf9cc cxxbridge1$str$ptr + 3274432\n14  chromedriver                        0x0000000102915138 cxxbridge1$str$ptr + 3558956\n15  chromedriver                        0x00000001029152b4 cxxbridge1$str$ptr + 3559336\n16  chromedriver                        0x0000000102923fcc cxxbridge1$str$ptr + 3620032\n17  libsystem_pthread.dylib             0x000000018814ef94 _pthread_start + 136\n18  libsystem_pthread.dylib             0x0000000188149d34 thread_start + 8", "trace": "self = <Test.test_E2E.TestEmbibe object at 0x102c5be90>\n\n    @pytest.mark.usefixtures(\"setup\", \"log_on_failure\")\n    @pytest.mark.practice\n    def test_practice_author_books(self):\n        log = self.getLogger()\n        self.test_sign_in_password()\n        ph = PracticeHomePage(self.driver)\n>       ph.author_books()\n\nTest/test_E2E.py:330: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nPageObject/practice_home_page.py:55: in author_books\n    self.practice_taking()\nPageObject/practice_home_page.py:84: in practice_taking\n    if question_element.is_displayed():\n../../.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:252: in is_displayed\n    return self.parent.execute_script(f\"/* isDisplayed */return ({isDisplayed_js}).apply(null, arguments);\", self)\n../../.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:414: in execute_script\n    return self.execute(command, {\"script\": script, \"args\": converted_args})[\"value\"]\n../../.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x1030ecd90>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"stale element reference\",\"message\":\"stale element reference: stale elemen...00018814ef94 _pthread_start + 136\\\\n18  libsystem_pthread.dylib             0x0000000188149d34 thread_start + 8\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\nE         (Session info: chrome=131.0.6778.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       0   chromedriver                        0x000000010292bb08 cxxbridge1$str$ptr + 3651580\nE       1   chromedriver                        0x0000000102924358 cxxbridge1$str$ptr + 3620940\nE       2   chromedriver                        0x000000010238c4b4 cxxbridge1$string$len + 89224\nE       3   chromedriver                        0x0000000102391398 cxxbridge1$string$len + 109420\nE       4   chromedriver                        0x0000000102393688 cxxbridge1$string$len + 118364\nE       5   chromedriver                        0x000000010240a950 cxxbridge1$string$len + 606500\nE       6   chromedriver                        0x000000010240a0fc cxxbridge1$string$len + 604368\nE       7   chromedriver                        0x00000001023c50b0 cxxbridge1$string$len + 321668\nE       8   chromedriver                        0x00000001023c5d00 cxxbridge1$string$len + 324820\nE       9   chromedriver                        0x00000001028f6e4c cxxbridge1$str$ptr + 3435328\nE       10  chromedriver                        0x00000001028fa164 cxxbridge1$str$ptr + 3448408\nE       11  chromedriver                        0x00000001028de1c0 cxxbridge1$str$ptr + 3333812\nE       12  chromedriver                        0x00000001028faa24 cxxbridge1$str$ptr + 3450648\nE       13  chromedriver                        0x00000001028cf9cc cxxbridge1$str$ptr + 3274432\nE       14  chromedriver                        0x0000000102915138 cxxbridge1$str$ptr + 3558956\nE       15  chromedriver                        0x00000001029152b4 cxxbridge1$str$ptr + 3559336\nE       16  chromedriver                        0x0000000102923fcc cxxbridge1$str$ptr + 3620032\nE       17  libsystem_pthread.dylib             0x000000018814ef94 _pthread_start + 136\nE       18  libsystem_pthread.dylib             0x0000000188149d34 thread_start + 8\n\n../../.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: StaleElementReferenceException"}, "attachments": [{"name": "log", "source": "2a79a7c4-e7ab-40c5-93a9-556454dd7f16-attachment.txt", "type": "text/plain"}], "start": 1733825564529, "stop": 1733825608253, "uuid": "10b91fb5-4f1f-4907-b060-0149c13969d7", "historyId": "226dc780cdb5b95d6449cf24ebb06156", "testCaseId": "226dc780cdb5b95d6449cf24ebb06156", "fullName": "Test.test_E2E.TestEmbibe#test_practice_author_books", "labels": [{"name": "tag", "value": "practice"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "parentSuite", "value": "Test"}, {"name": "suite", "value": "test_E2E"}, {"name": "subSuite", "value": "TestEmbibe"}, {"name": "host", "value": "EBL-C02H385BQ6L4.local"}, {"name": "thread", "value": "10500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test.test_E2E"}]}